Repository capitec/omni-components, pull requests merged in 2022-10, with the labels that each got.

#40 Feature/text field
  custom-elements-manifest.config.js
  scripts/theme-variables-parser.mjs
  src/button/Button.stories.ts
  src/core/OmniFormElement.ts
  src/core/OmniInputStories.ts
  src/icon/Icon.stories.ts
  src/icons/Check.icon.ts
  src/icons/Close.icon.ts
  src/icons/EyeHidden.icon.ts
  src/icons/EyeVisible.icon.ts
  src/icons/Indeterminate.icon.ts
  src/icons/LockClosed.icon.ts
  src/icons/LockOpen.icon.ts
  src/icons/Minus.icon.ts
  src/icons/Plus.icon.ts
  src/numeric-field/NumericField.stories.ts
  src/numeric-field/NumericField.ts
  src/numeric-field/index.ts
  src/password-field/PasswordField.stories.ts
  src/password-field/PasswordField.ts
  src/password-field/index.ts
  src/styles/ComponentStyles.ts
  src/text-field/TextField.stories.ts
  src/text-field/TextField.ts
  src/text-field/index.ts
  src/utils/StoryUtils.ts
  stories/Theming.stories.mdx
Labels: enhancement

#41 Version 0.2.0 Enhancements
  .eslintrc
  .storybook/main.js
  .storybook/preview.js
  CONTRIBUTING.md
  README.md
  custom-elements-manifest.config.js
  package-lock.json
  package.json
  scripts/theme-variables-parser.mjs
  src/button/Button.stories.ts
  src/button/Button.ts
  src/button/README.md
  src/check/Check.ts
  src/check/README.md
  src/chip/Chip.ts
  src/chip/README.md
  src/core/DOMTreeElement.ts
  src/core/OmniElement.ts
  src/core/OmniFormElement.ts
  src/hyperlink/Hyperlink.ts
  src/hyperlink/README.md
  src/icon/Icon.stories.ts
  src/icon/Icon.ts
  src/icon/README.md
  src/icons/Check.icon.ts
  src/icons/Close.icon.ts
  src/icons/EyeHidden.icon.ts
  src/icons/EyeVisible.icon.ts
  src/icons/Indeterminate.icon.ts
  src/icons/Loading.icon.ts
  src/icons/LockClosed.icon.ts
  src/icons/LockOpen.icon.ts
  src/icons/Minus.icon.ts
  src/icons/Plus.icon.ts
  src/icons/README.md
  src/label/Label.ts
  src/label/README.md
  src/radio/README.md
  src/radio/Radio.ts
  src/render-element/README.md
  src/render-element/RenderElement.stories.ts
  src/render-element/RenderElement.ts
  src/render-element/index.ts
  src/styles/ComponentStyles.ts
  src/switch/README.md
  src/switch/Switch.ts
  src/utils/StoryUtils.ts
  stories/Iconography.stories.mdx
  stories/Welcome.stories.mdx
  test-runner-jest.config.js
Labels: documentation, enhancement

#43 Resource guide updates
  src/check/Check.ts
  src/chip/Chip.ts
  src/core/OmniElement.ts
  src/core/OmniFormElement.ts
  src/numeric-field/NumericField.ts
  src/password-field/PasswordField.ts
  src/text-field/TextField.ts
  themes/blue-theme.css
  themes/green-theme.css
  themes/red-theme.css
Labels: documentation

#44 Number field
  src/number-field/NumberField.stories.ts
  src/number-field/NumberField.ts
  src/number-field/index.ts
  src/numeric-field/NumericField.ts
Labels: enhancement
