Repository capitec/omni-components, pull requests merged in 2023-03, with the labels that each got.

#93 Alpha updates
  package-lock.json
  package.json
  src/button/Button.ts
  src/chip/Chip.ts
  src/chip/README.md
  src/color-field/ColorField.ts
  src/currency-field/CurrencyField.ts
  src/hyperlink/Hyperlink.ts
  src/hyperlink/README.md
  src/pin-field/PinField.ts
  src/radio/README.md
  src/radio/Radio.ts
  src/select/Select.ts
  src/switch/README.md
  src/switch/Switch.ts
Labels: bug, documentation

#94 73 change request add radiogroup component
  .tooling/eleventy/components.njk
  .tooling/eleventy/includes/nav.njk
  .tooling/scripts/eleventy/filters.js
  .tooling/tests/dynamic.spec.js
  custom-elements-manifest.config.js
  src/radio/RadioGroup.stories.ts
  src/radio/RadioGroup.ts
  src/radio/index.ts
  src/utils/LivePropertyEditor.ts
  src/utils/StoryRenderer.ts
  src/utils/StoryUtils.ts
Labels: bug, documentation, enhancement

#96 Play function fixes
  src/currency-field/CurrencyField.stories.ts
  src/email-field/EmailField.stories.ts
  src/password-field/PasswordField.stories.ts
  src/pin-field/PinField.stories.ts
  src/text-field/TextField.stories.ts
Labels: bug, documentation

#101 CSS & doc content updates
  .tooling/eleventy/assets/css/style.css
  .tooling/eleventy/assets/css/themes.css
  .tooling/eleventy/assets/images/lit-logo.svg
  .tooling/eleventy/index.njk
  INSTALLATION.md
Labels: documentation

#105 Jest test failure for ci environment
  src/calendar/Calendar.stories.ts
  src/calendar/Calendar.ts
  src/check/Check.stories.ts
  src/chip/Chip.stories.ts
  src/color-field/ColorField.stories.ts
  src/currency-field/CurrencyField.stories.ts
  src/email-field/EmailField.stories.ts
  src/number-field/NumberField.stories.ts
  src/password-field/PasswordField.stories.ts
  src/pin-field/PinField.stories.ts
  src/search-field/SearchField.stories.ts
Labels: bug, documentation
